name: Build multi-piattaforma

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build Windows executable
        run: pyinstaller --onefile --add-data "templates;templates" --add-data "static;static" --add-data "templates_html;templates_html" app.py

      - name: Upload Windows artifact
        uses: actions/upload-artifact@v3
        with:
          name: windows-executable
          path: dist/app.exe

  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install pyinstaller

      - name: Build macOS executable
        run: pyinstaller --onefile --add-data "templates:templates" --add-data "static:static" --add-data "templates_html:templates_html" app.py

      - name: Upload macOS artifact
        uses: actions/upload-artifact@v3
        with:
          name: macos-executable
          path: dist/app
